development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"].downcase %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"].downcase %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"].downcase %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"].downcase %>
